"""
Loader for settings.yaml - the one hand-edited settings file for the RGB/IR
sync POC (camera params, rig ROI, calibration/test tuning). See settings.yaml
itself for what each field means and why it's tunable.

Kept separate from config.yaml on purpose: config.yaml is auto-generated by
led_calibration.py (rewritten wholesale on every run), so nothing hand-edited
should live there.
"""

import os
import yaml

SETTINGS_PATH = "settings.yaml"


def load_settings(path=SETTINGS_PATH):
    with open(path, "r") as f:
        return yaml.safe_load(f)


def get_current_roi(settings, camera_name):
    """Look up the ROI pair for this camera (by device name, e.g. "Intel
    RealSense D435I") at whatever rig.current_setup is set to. Raises a clear
    error if this camera model has no ROI data at all yet, or if its entry
    for this setup was never filled in (still all zeros).

    Note: keyed by camera MODEL name, not individual physical unit - two
    distinct units of the same model share one block."""
    rig = settings["rig"]
    current_setup = rig["current_setup"]
    roi_by_camera = rig["roi"]

    if camera_name not in roi_by_camera:
        raise KeyError(
            "No ROI data yet for camera {!r} - add a block for it "
            "under settings.yaml's rig.roi (copy an existing camera's block "
            "for the expected shape). Known cameras: {}".format(
                camera_name, list(roi_by_camera.keys())
            )
        )

    roi_by_setup = roi_by_camera[camera_name]
    if current_setup not in roi_by_setup:
        raise KeyError(
            "rig.current_setup={!r} is not a key in rig.roi[{!r}]. "
            "Valid options: {}".format(current_setup, camera_name, list(roi_by_setup.keys()))
        )

    roi_pair = {}
    for stream_name in ("ir", "rgb"):
        x, y, w, h = roi_by_setup[current_setup][stream_name]
        if w <= 0 or h <= 0:
            raise ValueError(
                "roi for camera={!r} setup={!r} stream={!r} is still (0,0,0,0) - "
                "run roi_picker.py for this physical setup with this camera "
                "connected and fill in the printed values into settings.yaml "
                "before running calibration.".format(camera_name, current_setup, stream_name)
            )
        roi_pair[stream_name] = (x, y, w, h)
    return roi_pair


def ensure_output_dir(settings):
    """Create paths.output_dir if it doesn't exist yet, return its path."""
    output_dir = settings["paths"]["output_dir"]
    os.makedirs(output_dir, exist_ok=True)
    return output_dir
